version: '3'

services:
  nginx:
    container_name: wp_sample_web
    image: nginx:mainline-alpine
    ports:
      - 8082:80
    depends_on:
      - wordpress
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  wordpress:
    container_name: wp_sample_app
    build: ./wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on: 
      - mysql
    volumes: 
      - ./app:/var/www/html
  
  mysql:
    container_name: wp_sample_db
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes: 
      - wp_sample_data:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
  
volumes:
  wp_sample_data:
